{
 "title": "Microservices Overview",
 "tags": [
  "microservices",
  "opentelemetry"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests (cumulative count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(microcommerce_http_server_request_duration_seconds_count) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (P95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(microcommerce_http_server_request_duration_seconds_bucket[1m])) by (le, service_name)) * 1000",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microcommerce_http_server_request_duration_seconds_count[1m])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "MediatR Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(microcommerce_mediatr_request_duration_milliseconds_bucket[1m])) by (le, request_name))",
     "legendFormat": "{{request_name}} (P50)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(microcommerce_mediatr_request_duration_milliseconds_bucket[1m])) by (le, request_name))",
     "legendFormat": "{{request_name}} (P95)"
    }
   ]
  },
  {
   "title": "MediatR Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(microcommerce_mediatr_requests_total[1m])) by (request_name, request_success)",
     "legendFormat": "{{request_name}} (success={{request_success}})"
    }
   ]
  },
  {
   "title": "MediatR Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(microcommerce_mediatr_requests_errors_total[1m])) by (request_name)",
     "legendFormat": "{{request_name}}"
    }
   ]
  }
 ]
}